# version: '3.9'

services:
  client:
    build: ./client
    environment:
      CHOKIDAR_USEPOLLING: true
    depends_on:
      - gateway
    ports:
      - "3000:3000"          
    volumes:
      - ./client:/client
      - /client/node_modules
  gateway:
    build: ./server/gateway
    volumes:
      - ./server/gateway:/gateway
      - /gateway/node_modules
    environment:
      CHOKIDAR_USEPOLLING: true
      PORT: 4000
    depends_on:
      user-service:
        condition: service_healthy
      post-service:
        condition: service_healthy
    ports:
      - "4000:4000"
  user-service: 
    build: ./server/user-service
    healthcheck:
      test: ["CMD", "curl", "-f", "-X", "POST", "http://localhost:4002/graphql", "-H", "Content-Type: application/json", "-d", "{\"query\":\"{__typename}\"}"]
      interval: 5s
      timeout: 2s
      retries: 5
    volumes:
      - ./server/user-service:/user-service
      - /server/user-service/node_modules
    environment:
      CHOKIDAR_USEPOLLING: true
      PORT: 4002
      DATABASE_URL: ${DATABASE_URL_USER_DB}
    depends_on:
      - user-db
    ports:
      - "4002:4002"
  post-service:
    build: ./server/post-service
    healthcheck:
      test: ["CMD", "curl", "-f", "-X", "POST", "http://localhost:4001/graphql", "-H", "Content-Type: application/json", "-d", "{\"query\":\"{__typename}\"}"]
      interval: 5s
      timeout: 2s
      retries: 5
    volumes:
      - ./server/post-service:/post-service
      - /server/post-service/node_modules
    environment:
      CHOKIDAR_USEPOLLING: true
      PORT: 4001
      DATABASE_URL: ${DATABASE_URL_POST_DB}
    depends_on:
      - post-db
    ports:
      - "4001:4001"
  
  user-db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_DB: user
    ports:
      - "5433:5432"
    volumes:
      - postgres_user_data:/var/lib/postgresql/data    
  post-db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_DB: post
    ports:
      - "5434:5432"
    volumes:
      - postgres_post_data:/var/lib/postgresql/data 

volumes:
  postgres_user_data:
  postgres_post_data: